framework:
    rate_limiter:
        codevault_access_ip:
            policy: sliding_window
            limit: 5
            interval: '10 minutes'
        codevault_access_email:
            policy: sliding_window
            limit: 3
            interval: '10 minutes'
        codevault_anthropic_ip:
            policy: sliding_window
            limit: 20
            interval: '1 hour'
        codevault_trial_ip:
            policy: sliding_window
            limit: 5
            interval: '1 hour'
